### ISSUE TITLE
where is model_v19.h5?

### ISSUE THREAD

**Issue by coder12333444** [nrchan/TCM_Herb_Server#1]
@nrchan  Hi,when I run the app.py .It occurs "OSError: No file or directory found at model_v19.h5".Can you give me a trained h5 file? Also, I want to train it myself. Can you give me the training code?
thanks

**Comment by nrchan** [comment]
Hi, the model: https://drive.google.com/file/d/1o1uehCDz3BRvcpc1t8U5BJTWzKonCzio/view?usp=sharing (link might expire in the future)

Unfortunately, I can't find the training code now, but it is written in Tensorflow, which can be trained by something like:

model = tf.keras.models.load_model(model_name, custom_objects={'KerasLayer':hub.KerasLayer})
model.compile(your parameter)
history = model.fit(your data)
